traefik:
  service:
    annotations:
      metallb.universe.tf/address-pool: ingress-pool

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints:
        - web
      matchRule: Host(`traefik.kube.mikrospace.se`)

  providers:
    kubernetesGateway:
      enabled: true

  gateway:
    listeners:
      web:
        namespacePolicy:
          from: All
