apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-l2-advert
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - ingress-pool
  nodeSelectors:
    - matchLabels:
        network-role: ingress
