apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: margarita-apps
spec:
  project: default
  source:
    repoURL: https://github.com/meDracula/FlatlineOps.git
    path: applicationsets/
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kube.mikrospace.se
    namespace: argocd

